```{r}
library(factoextra)
library(tidyverse)
```

##initial investigation
```{r}
panel.hist <- function(x, ...) {
  usr <- par("usr")
  on.exit(par(usr))
  par(usr = c(usr[1:2], 0, 1.5) )
  h <- hist(x, plot = FALSE)
  breaks <- h$breaks
  nB <- length(breaks)
  y <- h$counts
  y <- y/max(y)
  rect(breaks[-nB], 0, breaks[-1], y, col = "green", ...)
}
```

```{r}
pairs(iris[,1:4],diag.panel=panel.hist, pch=21, bg = c("red","green","blue")[iris$V5],oma=c(5,5,6,10))
legend("right",legend=1:3, fill=c("red","green","blue"),xpd=NA,cex=0.6)
title("Scatter Plot Matrix Of the iris data")
```
###Cluster Analysis
```{r}
d1=dist(iris[,1:4],method="euclidean",diag = T,upper = T)
```

##Number of clusters
#ESS and BGSS (Figuare 1)
```{r}
k=c(2,3,4,5)
ESS=function(data,k){
  km<-kmeans(data,centers=k)
  return(km$tot.withinss)
}
BGSS=function(data,k){
  km<-kmeans(data,centers=k)
  return(km$betweenss/km$totss)
}
```
```{r}
set.seed(1234)
par(mfrow=c(1,2))
plot(x=k,y=c(ESS(iris[,1:4],k[1]),ESS(iris[,1:4],k[2]),ESS(iris[,1:4],k[3]),ESS(iris[,1:4],k[4])), main = 'ESS', xlab = 'k', ylab = '',type = 'l',col='red')

plot(x=k,y=c(BGSS(iris[,1:4],k[1]),BGSS(iris[,1:4],k[2]),BGSS(iris[,1:4],k[3]),BGSS(iris[,1:4],k[4])), main = 'BGSS', xlab = 'k', ylab = '',type = 'l',col='blue')
```
#####K-means#####
```{r}
km_3<-kmeans(iris[,1:4],centers=3)
km_2<-kmeans(iris[,1:4],centers=2)
km_4<-kmeans(iris[,1:4],centers=4)
group<-km_3$cluster
group4<-km_4$cluster
group2<-km_2$cluster
```
```{r}
iris.kmeans3<-cbind(iris,group)
iris.kmeans4<-cbind(iris,group4)
iris.kmeans2<-cbind(iris,group2)
```

##by k mean clustering (figure 2)
```{r}
pairs(iris.kmeans3[,1:4], pch=21, bg = c("red","green","blue")[iris.kmeans3$group],oma=c(5,5,6,10))
legend("right",legend=1:3, fill=c("red","green","blue"),xpd=NA,cex=0.6)
title("Scatter Plot Matrix of the iris Data with 3 clusters")
```
##k=4 (Figure 3)
```{r}
pairs(iris.kmeans4[,1:4], pch=21, bg = c("red","green","blue","yellow")[iris.kmeans4$group4],oma=c(5,5,6,10))
legend("right",legend=1:4, fill=c("red","green","blue","yellow"),xpd=NA,cex=0.6)
title("Scatter Plot Matrix of the iris Data with 4 clusters")
```
##k=2 (figure 4)
```{r}
pairs(iris.kmeans2[,1:4], pch=21, bg = c("red","green")[iris.kmeans2$group2],oma=c(5,5,6,10))
legend("right",legend=1:2, fill=c("red","green"),xpd=NA,cex=0.6)
title("Scatter Plot Matrix of the iris Data with 2 clusters")
```

```{r}
write.csv(iris.kmeans3,"C:/Users/Admin/Desktop/SFU Fall 2022/STAT 452/Project 1/iris/iris.kmeans3.csv")
```

#####Hierarchical Clustering#######
##AVerage Linkage Method
```{r}
aver<-hclust(d=d1, method="average")
fviz_dend(aver, cex=0.5, k=3, main="Average Linkage", color_labels_by_k = TRUE, rect=TRUE)
```
```{r}
average_group<-cutree(aver,k=3)
table(average_group)
iris.aver<-cbind(iris,average_group)
```
```{r}
write.csv(iris.aver,"C:/Users/Admin/Desktop/SFU Fall 2022/STAT 452/Project 1/iris/iris.aver.csv")
```
##Complete linkage
```{r}
comp<-hclust(d=d1, method="complete")
fviz_dend(comp, cex=0.5, k=3, main="Complete linkage", color_labels_by_k = TRUE, rect=TRUE)
```
```{r}
complete_group<-cutree(comp,k=3)
table(complete_group)
iris.complete<-cbind(iris,complete_group)
```
```{r}
write.csv(iris.complete,"C:/Users/Admin/Desktop/SFU Fall 2022/STAT 452/Project 1/iris/iris.complete.csv")
```
##Single Linkage
```{r}
single<-hclust(d=d1, method="single")
fviz_dend(single, cex=0.5, k=3, main="Single Linkage", color_labels_by_k = TRUE, rect=TRUE)
```
```{r}
single_group<-cutree(single,k=3)
table(single_group)
iris.single<-cbind(iris,single_group)
```
```{r}
write.csv(iris.single,"C:/Users/Admin/Desktop/SFU Fall 2022/STAT 452/Project 1/iris/iris.single.csv")
```

########### K-nearest neighbors ########
```{r}
library(class)
```

```{r}
set.seed(6666)
```
```{r}
iris.order <- runif(nrow(iris))
```
```{r}
iris.2 <- iris[order(iris.order),]
```


```{r}
normalized.iris = scale(iris.2[,1:4])
```

```{r}
iris_train <- normalized.iris[1:105,]
iris_test <- normalized.iris[106:150,]
```

```{r}
Y_train <- iris.2[1:105, 5]
Y_test <- iris.2[106:150, 5]
```

```{r}
knn_1 <- knn(train=iris_train, test=iris_test, cl=Y_train, k=1)
table(Y_test, knn_1)
```








